name: Comment on finished suite
on:
    check_run:

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{github.event.check_run.check_suite.pull_requests[0].number}}
          body: "/retest"
          reactions: '+1'
